apiVersion: v1
kind: Service
metadata:
  name: mongo-comments-clusterip-srv
spec:
  selector:
    app: mongo-comments
  ports:
    - name: mongo-comments
      protocol: TCP
      port: 27018
      targetPort: 27017