apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-comments
  name: mongo-comments-nodeport-svc
spec:
  ports:
  - port: 27018
    protocol: TCP
    targetPort: 27017
    nodePort: 30001
  selector:
    app: mongo-comments
  type: NodePort

