apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  labels:
    app: client
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v1.0
  template:
    metadata:
      labels:
        app: client
        version: v1.0
    spec:
      containers:
        - name: client
          image: adaptivenetlab/research:clientv2
          env:
          - name: REACT_APP_NODE_ENV
            value: 'Kubernetes Environment'
          - name: REACT_APP_POST_BASE_URL
            value: 'http://posts.com'
          - name: REACT_APP_COMMENT_BASE_URL
            value: 'http://posts.com'
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
