apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-nuxt-v1
  labels:
    app: client
    version: nuxt-1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: nuxt-1.0
  template:
    metadata:
      labels:
        app: client
        version: nuxt-1.0
    spec:
      containers:
        - name: client
          image: adaptivenetlab/research:nuxtv2
          env:
          - name: POST_BASE_URL
            value: 'http://posts-clusterip-srv.postsapp:4000'
          - name: COMMENT_BASE_URL
            value: 'http://comments-srv.postsapp:4001'
          - name: POST_ID
            value: 'none'
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000