apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: adaptivenetlab/research:comments
          env:
          - name: MESSAGE
            value: 'This is Kubernetes Environment!'
          - name: PORT
            value: "4001"
          ## MONGO DB ENVIRONMENT
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: user
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: password
          - name: DB_HOST
            value: mongo-comments-clusterip-srv.postsapp.svc.cluster.local
          - name: DB_NAME
            value: comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
