apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: adaptivenetlab/research:postsv2
          env:
          - name: MESSAGE
            value: 'This is Kubernetes Environment!'
          - name: PORT
            value: "4000"
          ## MONGO DB ENVIRONMENT
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          - name: DB_HOST
            value: mongo-posts-clusterip-srv.postsapp.svc.cluster.local
          - name: DB_NAME
            value: posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
