apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv-posts
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo-posts
  storageClassName: standard