apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-posts
  name: mongo-posts-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30000
  selector:
    app: mongo-posts
  type: NodePort

