name: MicroSvcCICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Login to DockerHub
      uses : docker/login-action@v1
      with :
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Client
      id : docker_build1
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./client/Dockerfile
        tags: adaptivenetlab/research:client

    - name: Build & Push Comments
      id : docker_build2
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./comments/Dockerfile
        tags: adaptivenetlab/research:comments
        
    - name: Build & Push Posts
      id : docker_build3
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./posts/Dockerfile
        tags: adaptivenetlab/research:posts
